# Generated by Django 5.0.6 on 2024-06-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_vehicle_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='type_name',
        ),
    ]
